// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"time"
)

type Career struct {
	Jobid       int64     `json:"jobid"`
	Company     string    `json:"company"`
	Position    string    `json:"position"`
	Jobtype     string    `json:"jobtype"`
	Description string    `json:"description"`
	Startdate   time.Time `json:"startdate"`
	Enddate     time.Time `json:"enddate"`
}

type Profile struct {
	Profileid   int64  `json:"profileid"`
	Userid      int64  `json:"userid"`
	Fullname    string `json:"fullname"`
	Age         int32  `json:"age"`
	Gender      string `json:"gender"`
	Address     string `json:"address"`
	Phonenumber string `json:"phonenumber"`
}

type User struct {
	Userid      int64        `json:"userid"`
	Username    string       `json:"username"`
	Email       string       `json:"email"`
	Phonenumber string       `json:"phonenumber"`
	Password    string       `json:"password"`
	Role        string       `json:"role"`
	Createdat   sql.NullTime `json:"createdat"`
	Updatedat   sql.NullTime `json:"updatedat"`
}
