CREATE TABLE IF NOT EXISTS users (
    UserID BIGSERIAL PRIMARY KEY,
    Username VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    PhoneNumber VARCHAR(20) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Role VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);

CREATE TABLE IF NOT EXISTS Profile (
    ProfileID  BIGSERIAL PRIMARY KEY,
    UserID BIGSERIAL NOT NULL,
    FullName VARCHAR(255) NOT NULL,
    Age INT NOT NULL,
    Gender VARCHAR(10) NOT NULL,
    Address VARCHAR(255) NOT NULL,
    PhoneNumber VARCHAR(20) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES users(UserID)
);

CREATE TABLE IF NOT EXISTS Career (
    JobID  BIGSERIAL PRIMARY KEY,
    Company VARCHAR(255) NOT NULL,
    Position VARCHAR(255) NOT NULL,
    Jobtype  VARCHAR(255) NOT NULL,
    Description VARCHAR(255) NOT NULL,
    StartDate DATE  NOT NULL ,
    EndDate DATE NOT NULL
);